In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [3]:
credit_card = pd.read_csv("creditcard.csv")
credit_card.head(10)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0
5,2,-0.425966,0.960523,1.141109,-0.168252,0.420987,-0.029728,0.476201,0.260314,-0.568671,...,-0.208254,-0.559825,-0.026398,-0.371427,-0.232794,0.105915,0.253844,0.081080,3.67,0.0
6,4,1.229658,0.141004,0.045371,1.202613,0.191881,0.272708,-0.005159,0.081213,0.464960,...,-0.167716,-0.270710,-0.154104,-0.780055,0.750137,-0.257237,0.034507,0.005168,4.99,0.0
7,7,-0.644269,1.417964,1.074380,-0.492199,0.948934,0.428118,1.120631,-3.807864,0.615375,...,1.943465,-1.015455,0.057504,-0.649709,-0.415267,-0.051634,-1.206921,-1.085339,40.80,0.0
8,7,-0.894286,0.286157,-0.113192,-0.271526,2.669599,3.721818,0.370145,0.851084,-0.392048,...,-0.073425,-0.268092,-0.204233,1.011592,0.373205,-0.384157,0.011747,0.142404,93.20,0.0
9,9,-0.338262,1.119593,1.044367,-0.222187,0.499361,-0.246761,0.651583,0.069539,-0.736727,...,-0.246914,-0.633753,-0.120794,-0.385050,-0.069733,0.094199,0.246219,0.083076,3.68,0.0

In [4]:
credit_card.columns

Index(['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
       'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount',
       'Class'],
      dtype='object')

In [5]:
 credit_card.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 126842 entries, 0 to 126841
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    126842 non-null  int64
 1   V1      126842 non-null  float64
 2   V2      126842 non-null  float64
 3   V3      126842 non-null  float64
 4   V4      126842 non-null  float64
 5   V5      126842 non-null  float64
 6   V6      126842 non-null  float64
 7   V7      126842 non-null  float64
 8   V8      126842 non-null  float64
 9   V9      126841 non-null  float64
 10  V10     126841 non-null  float64
 11  V11     126841 non-null  float64
 12  V12     126841 non-null  float64
 13  V13     126841 non-null  float64
 14  V14     126841 non-null  float64
 15  V15     126841 non-null  float64
 16  V16     126841 non-null  float64
 17  V17     126841 non-null  float64
 18  V18     126841 non-null  float64
 19  V19     126841 non-null  float64
 20  V20     126841 non-null  float64
 21  V21     126841 non-null  float64
 22  V22     126841 non-null  float64
 23  V23     126841 non-null  float64
 24  V24     126841 non-null  float64
 25  V25     126841 non-null  float64
 26  V26     126841 non-null  float64
 27  V27     126841 non-null  float64
 28  V28     126841 non-null  float64
 29  Amount  126841 non-null  float64
 30  Class   126841 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 30.0 MB

In [6]:
pd.isnull(credit_card).sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        1
V10       1
V11       1
V12       1
V13       1
V14       1
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [7]:
credit_card.shape

(126842, 31)

In [9]:
credit_card['Class'].value_counts()

0.0    126581
1.0       260
Name: Class, dtype: int64

In [10]:
credit_card.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,126842.000000,126842.000000,126842.000000,126842.000000,126842.000000,126842.000000,126842.000000,126842.000000,126842.000000,126841.000000,...,126841.000000,126841.000000,126841.000000,126841.000000,126841.000000,126841.000000,126841.000000,126841.000000,126841.000000,126841.000000
mean,48881.555471,-0.250296,-0.001127,0.676304,0.148385,-0.283756,0.084388,-0.115995,0.062204,-0.085131,...,-0.036336,-0.115196,-0.034406,0.011828,0.130663,0.026336,0.000705,0.001992,93.188432,0.002050
std,19649.937416,1.829039,1.626218,1.282556,1.330422,1.321164,1.288594,1.179549,1.214806,1.094140,...,0.725258,0.636708,0.607599,0.594706,0.438661,0.491506,0.391879,0.314250,252.555507,0.045229
min,0.000000,-56.407510,-72.715728,-33.680984,-5.172595,-42.147898,-26.160506,-31.764946,-73.216718,-9.283925,...,-34.830382,-10.933144,-44.807735,-2.836627,-10.295397,-2.534330,-22.565679,-11.710896,0.000000,0.000000
25%,36482.250000,-1.020532,-0.579207,0.172332,-0.707829,-0.904614,-0.657324,-0.602986,-0.133209,-0.712703,...,-0.225578,-0.543722,-0.173189,-0.324377,-0.135269,-0.324291,-0.060666,-0.004312,6.510000,0.000000
50%,50705.500000,-0.262156,0.093233,0.751957,0.175554,-0.315813,-0.169537,-0.066014,0.078508,-0.146805,...,-0.058833,-0.092464,-0.046422,0.068423,0.167306,-0.064471,0.011194,0.023518,24.950000,0.000000
75%,65183.000000,1.156809,0.761032,1.369928,1.005351,0.239889,0.471743,0.410132,0.371195,0.496674,...,0.116208,0.304561,0.082875,0.408717,0.418917,0.291984,0.085445,0.077301,83.570000,0.000000
max,78123.000000,1.960497,18.902453,9.382558,16.715537,34.801666,22.529298,36.677268,20.007208,15.594995,...,27.202839,10.503090,19.002942,4.016342,5.541598,3.517346,12.152401,33.847808,19656.530000,1.000000

In [11]:
legit = credit_card[credit_card.Class==0]
fraud = credit_card[credit_card.Class==1]

In [12]:
legit

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126836,78120,1.254408,0.300375,0.288163,0.699809,-0.432957,-1.086648,0.040038,-0.163694,0.139474,...,-0.295514,-0.889107,0.136353,0.320564,0.192632,0.097012,-0.027858,0.029412,2.69,0.0
126837,78120,-0.701012,0.875241,1.000367,-0.013043,-0.476499,-0.437192,0.409603,0.378708,-0.441322,...,0.069201,-0.081844,0.152562,-0.126886,-0.530613,0.149956,-0.027016,0.099560,77.50,0.0
126838,78121,1.222694,0.293417,0.744617,0.742438,-0.704253,-1.288324,0.101152,-0.262905,-0.053045,...,-0.217619,-0.613095,0.197303,0.923791,0.160025,0.060173,-0.025737,0.025328,1.98,0.0
126839,78122,-2.273393,1.733770,-0.808175,-1.843853,-1.183736,-0.769606,-0.709206,1.175721,0.279479,...,0.179541,-0.143411,0.046580,-0.329623,-0.485846,-0.217190,-1.484897,-0.331272,10.69,0.0
126840,78122,1.282279,-0.614161,0.397264,-0.722294,-0.916397,-0.256313,-0.635567,0.065928,-1.047057,...,-0.370228,-0.631999,0.123472,0.024604,0.024432,0.961578,-0.047010,-0.002245,20.00,0.0

In [13]:
fraud

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
541,406,-2.312227,1.951992,-1.609851,3.997906,-0.522188,-1.426545,-2.537387,1.391657,-2.770089,...,0.517232,-0.035049,-0.465211,0.320198,0.044519,0.177840,0.261145,-0.143276,0.00,1.0
623,472,-3.043541,-3.157307,1.088463,2.288644,1.359805,-1.064823,0.325574,-0.067794,-0.270953,...,0.661696,0.435477,1.375966,-0.293803,0.279798,-0.145362,-0.252773,0.035764,529.00,1.0
4920,4462,-2.303350,1.759247,-0.359745,2.330243,-0.821628,-0.075788,0.562320,-0.399147,-0.238253,...,-0.294166,-0.932391,0.172726,-0.087330,-0.156114,-0.542628,0.039566,-0.153029,239.93,1.0
6108,6986,-4.397974,1.358367,-2.592844,2.679787,-1.128131,-1.706536,-3.496197,-0.248778,-0.247768,...,0.573574,0.176968,-0.436207,-0.053502,0.252405,-0.657488,-0.827136,0.849573,59.00,1.0
6329,7519,1.234235,3.019740,-4.304597,4.732795,3.624201,-1.357746,1.713445,-0.496358,-1.282858,...,-0.379068,-0.704181,-0.656805,-1.632653,1.488901,0.566797,-0.010016,0.146793,1.00,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124036,77154,-0.715414,0.608590,1.155501,-0.267565,-0.563748,-0.618898,0.698308,0.069837,-0.133341,...,0.130749,0.239389,-0.090227,0.411572,-0.216126,0.353896,-0.062361,0.008433,129.00,1.0
124087,77171,1.118560,1.291858,-1.298805,2.135772,0.772204,-1.147291,0.390578,-0.107072,-0.038339,...,-0.346374,-0.663588,-0.102326,0.017911,0.650302,-0.332366,0.105949,0.128124,1.00,1.0
124115,77182,-1.410852,2.268271,-2.297554,1.871331,0.248957,-1.208799,-1.358648,1.102916,-1.317364,...,0.155381,-0.614880,-0.196126,-0.464376,0.118473,-0.484537,0.373596,0.187657,1.00,1.0
124176,77202,-0.356326,1.435305,-0.813564,1.993117,2.055878,-0.543579,0.487691,0.085449,-0.536352,...,-0.312863,-0.687874,-0.267003,-1.158480,0.271460,-0.155397,0.114328,0.101526,1.00,1.0
125342,77627,-7.139060,2.773082,-6.757845,4.446456,-5.464428,-1.713401,-6.485365,3.409395,-3.053493,...,1.303250,-0.016118,-0.876670,0.382230,-1.054624,-0.614606,-0.766848,0.409424,106.90,1.0

In [14]:
legit.shape

(126581, 31)

In [15]:
fraud.shape

(260, 31)

In [35]:
legit_sample = legit.sample(n=260)
new_credit_card = pd.concat([legit_sample,fraud],axis=0)

In [37]:
new_credit_card

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
83752,60012,1.283482,0.226381,0.300176,0.507856,-0.232657,-0.702720,0.068106,-0.182510,0.059317,...,-0.284985,-0.829074,0.067920,-0.116151,0.285935,0.124405,-0.030055,0.015318,7.99,0.0
30548,35978,1.215920,0.372760,0.294943,0.632968,-0.102460,-0.579101,0.067577,-0.114808,-0.104472,...,-0.250740,-0.643759,0.148359,0.052503,0.174239,0.121599,-0.000654,0.029095,0.89,0.0
71109,54160,-1.221491,0.584432,0.260960,-2.183469,0.148069,-0.353845,0.134643,0.220526,-1.162636,...,0.182635,0.720601,-0.387976,-0.799762,0.172382,-0.287630,0.301891,0.010734,23.90,0.0
117637,74750,-2.698587,4.392193,-3.591526,1.133280,-0.286535,-1.997644,0.071772,0.756309,1.558723,...,-0.319303,-0.208048,0.448087,0.215828,0.063653,-0.360382,1.140280,0.614042,0.89,0.0
102432,68203,-0.165301,-0.362899,1.261673,0.194327,-1.204987,0.534393,0.542481,0.117966,0.623706,...,0.107572,0.319238,0.773378,0.154295,-1.445244,0.826045,0.117443,0.185274,222.32,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124036,77154,-0.715414,0.608590,1.155501,-0.267565,-0.563748,-0.618898,0.698308,0.069837,-0.133341,...,0.130749,0.239389,-0.090227,0.411572,-0.216126,0.353896,-0.062361,0.008433,129.00,1.0
124087,77171,1.118560,1.291858,-1.298805,2.135772,0.772204,-1.147291,0.390578,-0.107072,-0.038339,...,-0.346374,-0.663588,-0.102326,0.017911,0.650302,-0.332366,0.105949,0.128124,1.00,1.0
124115,77182,-1.410852,2.268271,-2.297554,1.871331,0.248957,-1.208799,-1.358648,1.102916,-1.317364,...,0.155381,-0.614880,-0.196126,-0.464376,0.118473,-0.484537,0.373596,0.187657,1.00,1.0
124176,77202,-0.356326,1.435305,-0.813564,1.993117,2.055878,-0.543579,0.487691,0.085449,-0.536352,...,-0.312863,-0.687874,-0.267003,-1.158480,0.271460,-0.155397,0.114328,0.101526,1.00,1.0
125342,77627,-7.139060,2.773082,-6.757845,4.446456,-5.464428,-1.713401,-6.485365,3.409395,-3.053493,...,1.303250,-0.016118,-0.876670,0.382230,-1.054624,-0.614606,-0.766848,0.409424,106.90,1.0

In [36]:
new_credit_card['Class'].value_counts()

0.0    260
1.0    260
Name: Class, dtype: int64

In [38]:
new_credit_card.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,50267.315385,-0.362587,0.090455,0.583629,0.070853,-0.468408,0.087178,-0.042804,0.157743,-0.088328,...,0.035525,0.017050,-0.051447,-0.041694,-0.014678,0.118124,0.034301,-0.019265,-0.006237,107.706731
1.0,41834.653846,-5.671074,3.981496,-7.244578,4.545756,-4.025447,-1.498972,-5.996932,1.531671,-2.627267,...,0.241923,1.274635,-0.321896,-0.113359,-0.107386,0.199859,0.058654,0.497977,0.081654,116.897692

In [39]:
X = new_credit_card.drop('Class',axis=1)
Y = new_credit_card['Class']

In [44]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=2)

In [45]:
model =LogisticRegression()

In [49]:
X_train_prediction.shape

(416,)

In [50]:
Y_train.shape

(416,)

In [46]:
model.fit(X_train,Y_train)
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction,Y_train)
print("Accuracy of training data :",training_data_accuracy)

Accuracy of training data : 0.9495192307692307

In [51]:
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction,Y_test)
print("Accuracy of test data:", test_data_accuracy)

Accuracy of test data: 0.9423076923076923